### ISSUE TITLE
MacOS error:  dyld: lazy symbol binding failed:  ai.djl.pytorch 1.7.0 

### ISSUE THREAD

**Issue by macster110** [awslabs/djl#332]
_## Question
Really enjoying using this library for deep learning  but I have come across an error I cannot seem to solve. I am trying to load a model and get the following errors when I call predictor.predict

```
dyld: lazy symbol binding failed: Symbol not found: __ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
  Referenced from: /Users/au671271/.djl.ai/pytorch/1.7.0-SNAPSHOT-cpu-osx-x86_64/0.8.0-SNAPSHOT-cpu-libdjl_torch.dylib
  Expected in: /Users/au671271/.djl.ai/pytorch/1.7.0-SNAPSHOT-cpu-osx-x86_64/libc10.dylib

dyld: Symbol not found: __ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
  Referenced from: /Users/au671271/.djl.ai/pytorch/1.7.0-SNAPSHOT-cpu-osx-x86_64/0.8.0-SNAPSHOT-cpu-libdjl_torch.dylib
  Expected in: /Users/au671271/.djl.ai/pytorch/1.7.0-SNAPSHOT-cpu-osx-x86_64/libc10.dylib
```
I originally thought this might be an error in my g++ toolchain, however, if I downgrade the version to of a.djl.pytorch in Maven, to 1.6.0 the error no longer occurs. 

```
	<dependency>
		<groupId>ai.djl.pytorch</groupId>
		<artifactId>pytorch-native-auto</artifactId>
		<version>1.7.0-SNAPSHOT</version> <!--v1.6 works, 1.7 does or 1.7-SNAPSHOT does not-->
		<scope>runtime</scope>
	</dependency>_
```

I'm a bit lost on how to solve this? Does anyone have any tips?

The full code is [here](https://github.com/macster110/JTorch4PAM) and I was using the main class PyTorch2JavaTestdjl

Thanks in advance for any help.

**Comment by Jzow** [comment]
Hi, friend，from the exception, it seems to be a version dependency problem，Please wait patiently for the official djl team to ask you to answer this question，You can look at this url [bump up pytorch version](https://github.com/awslabs/djl/pull/310)

**Comment by frankfliu** [comment]
@macster110 Most likely is version mismatch.
pytorch-native:1.7.0 need to work with pytorch-engine:0.9.0-SNAPSHOT version. And be sure clean the cache:
1. rm -rf ~/.djl.ai/pytorch
2. ./gradlew clean

**Comment by macster110** [comment]
Thanks @Jzow and @frankfliu. You are right, updating my Maven pom.xml to 0.9.0-SNAPSHOT for all djl.ai dependecies did the trick. Thanks for the help!
