### ISSUE TITLE
 java.lang.NoSuchMethodError: ai.djl.repository.zoo.BaseModelLoader.<init>

### ISSUE THREAD

**Issue by gwlgmz** [awslabs/djl#478]
## Question

    public static void main(String[] args) throws MalformedModelException, ModelNotFoundException, IOException, TranslateException {

        String url = "https://pic3.zhimg.com/80/v2-79b66c1c903bbed8511e47289c9245c2_720w.jpg";
        BufferedImage img = getRemoteBufferedImage(url);

        Criteria<BufferedImage, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.OBJECT_DETECTION)
                        .setTypes(BufferedImage.class, DetectedObjects.class)
                        .optFilter("backbone", "resnet50")
                        .optProgress(new ProgressBar())
                        .build();

        try (ZooModel<BufferedImage, DetectedObjects> model = ModelZoo.loadModel(criteria)) {
            try (Predictor<BufferedImage, DetectedObjects> predictor = model.newPredictor()) {
                DetectedObjects detection = predictor.predict(img);
                System.out.println(detection);
            }
        }
    }

Run:
Exception in thread "main" java.lang.NoSuchMethodError: ai.djl.repository.zoo.BaseModelLoader.<init>(Lai/djl/repository/Repository;Lai/djl/repository/MRL;Ljava/lang/String;)V
	at ai.djl.pytorch.zoo.cv.classification.ImageClassificationModelLoader.<init>(ImageClassificationModelLoader.java:63)
	at ai.djl.pytorch.zoo.cv.classification.Resnet.<init>(Resnet.java:36)
	at ai.djl.pytorch.zoo.PtModelZoo.<clinit>(PtModelZoo.java:33)
	at ai.djl.pytorch.zoo.PtZooProvider.getModelZoo(PtZooProvider.java:26)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:123)

**Comment by frankfliu** [comment]
@gwlgmz 
Can you share you build script, gradle or maven pom file?

Which version of DJL are you using?

NoSuchMethodError usually caused by classpath issue. Your runtime classpath may contains duplicate jars, some of them are old version of DJL, a old version BaseModelLoader.class was loaded and it doesn't have new method.

**Comment by lanking520** [comment]
@gwlgmz close this issue for now. The current resolution is you are using DJL packages in different versions for compile and running. Please make sure they are matched: DJL 0.8.0 code may not work on 0.9.0 and same applies to the other way. As long as the versions are match, this issue should be gone. Please feel free to reopen this issue if you have more information about the cofiguration.
